### ISSUE TITLE
handle server_config unexceptedly when cli parameter contains "="

### ISSUE THREAD

**Issue by AmazingSkyLine** [triton-inference-server/model_analyzer#279]
Hi~guys
I have run model_analyzer in local mode, and I want to run tritonserver using tensorflow backend version 2, so I set server_config as below:
```yaml
    triton_server_flags:
      backend_config: tensorflow,version=2
      strict_model_config: false
```
But when I execute model-analyzer, tritonserver has error in log:
`--backend-config option format is '<backend name>,<setting>=<value>'. Got tensorflow,version`

And I see source code in server_local.py:

```python
        if self._server_path:
            # Create command list and run subprocess
            cmd = [self._server_path]
            cmd += self._server_config.to_cli_string().replace('=', ' ').split()
```
There just replace '=' with ''

So how can I set a server_config parameter with '='?
