### ISSUE TITLE
Sweep Over Model Parameters

### ISSUE THREAD

**Issue by jishminor** [triton-inference-server/model_analyzer#385]
Version 22.03

In the configuration for `model_config_parameters` i'm receiving an error when specifying to sweep over model parameters. In this case I would like to sweep over the number of threads used for executing operations in the Tensorflow backend.

Here is my config:
```yaml
model_repository: /model-test/triton_model_repo/

run_config_search_max_concurrency: 16
profile_models:
  vggish:
    model_config_parameters:
        max_batch_size: [1, 5, 10]
        instance_group:
        -
            kind: KIND_CPU
            count: [1, 2, 3, 4]
        parameters:
            key: TF_NUM_INTRA_THREADS
            value:
                string_value: [1]
```

When running this test using the command:
```bash
model-analyzer profile --config /model-test/profile_config.yml --collect-cpu-metrics --override-output-model-repository
```

I get the error from the parser:
```
2022-04-21 21:59:25.205 ERROR[entrypoint.py:317] Model Analyzer encountered an error: Failed to set the value for field "profile_models". Error: Value "{'vggish': {'model_config_parameters': {'max_batch_size': [1, 5, 10], 'instance_group': [{'kind': 'KIND_CPU', 'count': [1, 2, 3, 4]}], 'parameters': {'key': 'TF_NUM_INTRA_THREADS', 'value': {'string_value': [1]}}}}}" cannot be set for field "profile_models". This field allows multiple types of values. You only need to fix one of the errors below:
	* Field "profile_models.vggish.model_config_parameters.parameters" is a sweep parameter. If you intend to provide a sweep parameter, fix the number one error, otherwise fix error number two: 1. Value "{'key': 'TF_NUM_INTRA_THREADS', 'value': {'string_value': [1]}}" cannot be set for field "profile_models.vggish.model_config_parameters.parameters". This field allows multiple types of values. You only need to fix one of the errors below:
	* 	* Field "profile_models.vggish.model_config_parameters.parameters.key" is a sweep parameter. If you intend to provide a sweep parameter, fix the number one error, otherwise fix error number two: 1. Value "TF_NUM_INTRA_THREADS" cannot be set for field "profile_models.vggish.model_config_parameters.parameters.key". This field allows multiple types of values. You only need to fix one of the errors below:
	* 	* 	* Value for field "profile_models.vggish.model_config_parameters.parameters.key" should be an object. Type <class 'str'> is provided instead.
	* 	* 	* Value "TF_NUM_INTRA_THREADS" for field "profile_models.vggish.model_config_parameters.parameters.key" should be None
	* 	*  2. Value for field "profile_models.vggish.model_config_parameters.parameters.key" must be a list, value is "TF_NUM_INTRA_THREADS".
	* 	* Value "{'key': 'TF_NUM_INTRA_THREADS', 'value': {'string_value': [1]}}" for field "profile_models.vggish.model_config_parameters.parameters" should be None
	*  2. Value for field "profile_models.vggish.model_config_parameters.parameters" must be a list, value is "{'key': 'TF_NUM_INTRA_THREADS', 'value': {'string_value': [1]}}".
	* Value for field "profile_models" must be a list, value is "{'vggish': {'model_config_parameters': {'max_batch_size': [1, 5, 10], 'instance_group': [{'kind': 'KIND_CPU', 'count': [1, 2, 3, 4]}], 'parameters': {'key': 'TF_NUM_INTRA_THREADS', 'value': {'string_value': [1]}}}}}".
	* The value for field "profile_models" should not be a dictionary, current value is "{'vggish': {'model_config_parameters': {'max_batch_size': [1, 5, 10], 'instance_group': [{'kind': 'KIND_CPU', 'count': [1, 2, 3, 4]}], 'parameters': {'key': 'TF_NUM_INTRA_THREADS', 'value': {'string_value': [1]}}}}}".
```

From this error it's a bit hard to decipher what is actually causing the issue.

The model config for this model is:
```
name: "vggish"
platform: "tensorflow_graphdef"
max_batch_size: 10
input [
  {
    name: "vggish/input_features"
    data_type: TYPE_FP32
    dims: [ 96, 64 ]
  }
]
output [
  {
    name: "vggish/embedding"
    data_type: TYPE_FP32
    dims: [ 128 ]
  }
]
parameters: {
key: "TF_NUM_INTRA_THREADS"
value: {
string_value:"2"
}
}
```

Is this expected behavior?

**Comment by jishminor** [comment]
I actually found an example of how the pbtxt translates to yaml in #361. Upon revising my model config params as per the following:
```yaml
model_repository: /model-test/triton_model_repo/

run_config_search_max_concurrency: 16
profile_models:
  vggish:
    model_config_parameters:
        max_batch_size: [1, 5, 10]
        instance_group:
        -
            kind: KIND_CPU
            count: [1, 2, 3, 4]
        parameters:
            TF_NUM_INTRA_THREADS:
                string_value: ["1", "2", "4", "8", "16", "32", "64"]
```

The parser no longer complained.
