### ISSUE TITLE
Does model_analyzer support running models(openvino model) concurrently on CPU?

### ISSUE THREAD

**Issue by ann-wzhao** [triton-inference-server/model_analyzer#572]
I want to **perf multi openvino models on CPU**, but don't find any related config parameters. I have read the doc as the blow .
![image](https://user-images.githubusercontent.com/84758182/205642506-439768d9-5699-414f-8c26-126a82195ded.png)

Could we pass instance_group parameters under **Multi-Model Search Mode**?
Thank you!

**Comment by nv-braf** [comment]
You can set the `cpu_only` flag to `true` in the config file you specify for the profile. You can find an example of this in our documentation (see config.md). For a multi-model run it will look like:
```
profile_models:
  model_1:
    cpu_only: true
  model_2:
    cpu_only: true
```
