### ISSUE TITLE
Model-anaylzer does not support parameters specific to onnx models 

### ISSUE THREAD

**Issue by dmastapkovich** [triton-inference-server/model_analyzer#655]
Hello 
I can't get the onnx model-specific parameters into the `model_config_parameters` field:
Model config:
```
name: "custom_model"
backend: "onnxruntime"
default_model_filename: "model.onnx"
max_batch_size: 16
input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [ -1 ]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [ -1 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 10 ]
  }
]

# parameters [
#   {
#     key: "intra_op_thread_count"
#     value: { string_value: "3" }
#   }
# ]
```
Model-anaylzer config:
```
model_repository: /models
triton_launch_mode: docker

profile_models:
  model_inference:
    model_config_parameters:
      dynamic_batching:
        max_queue_delay_microseconds: [10, 100, 500, 1000, 10000, 50000, 100000]
      instance_group:
       - kind: KIND_CPU
         count: [1, 2, 3, 4]
      parameters:
        - key: "intra_op_thread_count"
          value: 
            string_value: [1, 2, 3]

perf_analyzer_flags:
  input-data: /workspace/model_analyzer_configs/input_data.json

override_output_model_repository: true
output_model_repository_path: /home/user/output

```
Logs:

```
Model Analyzer] Model Analyzer encountered an error: Failed to set the value for field "profile_models". Error: Value "{'model_inference': {'cpu_only': True, 'model_config_parameters': {'dynamic_batching': {'max_queue_delay_microseconds': [10, 100, 500, 1000, 10000, 50000, 100000]}, 'instance_group': [{'kind': 'KIND_CPU', 'count': [1, 2, 3, 4]}], 'parameters': [{'key': 'intra_op_thread_count', 'value': {'string_value': [1, 2, 3]}}]}}}" cannot be set for field "profile_models". This field allows multiple types of values. You only need to fix one of the errors below:
        * Field "profile_models.model_inference.model_config_parameters.parameters" is a sweep parameter. If you intend to provide a sweep parameter, fix the number one error, otherwise fix error number two: 1. Value "[{'key': 'intra_op_thread_count', 'value': {'string_value': [1, 2, 3]}}]" cannot be set for field "profile_models.model_inference.model_config_parameters.parameters". This field allows multiple types of values. You only need to fix one of the errors below: 
        *       * Value for field "profile_models.model_inference.model_config_parameters.parameters" should be an object. Type <class 'list'> is provided instead.  
        *       * Value "[{'key': 'intra_op_thread_count', 'value': {'string_value': [1, 2, 3]}}]" for field "profile_models.model_inference.model_config_parameters.parameters" should be None  
        *  2. Value "{'key': 'intra_op_thread_count', 'value': {'string_value': [1, 2, 3]}}" cannot be set for field "profile_models.model_inference.model_config_parameters.parameters". This field allows multiple types of values. You only need to fix one of the errors below: 
        *       * Field "profile_models.model_inference.model_config_parameters.parameters.key" is a sweep parameter. If you intend to provide a sweep parameter, fix the number one error, otherwise fix error number two: 1. Value "intra_op_thread_count" cannot be set for field "profile_models.model_inference.model_config_parameters.parameters.key". This field allows multiple types of values. You only need to fix one of the errors below:  
        *       *       * Value for field "profile_models.model_inference.model_config_parameters.parameters.key" should be an object. Type <class 'str'> is provided instead.   
        *       *       * Value "intra_op_thread_count" for field "profile_models.model_inference.model_config_parameters.parameters.key" should be None   
        *       *  2. Value for field "profile_models.model_inference.model_config_parameters.parameters.key" must be a list, value is "intra_op_thread_count".  
        *       * Value "{'key': 'intra_op_thread_count', 'value': {'string_value': [1, 2, 3]}}" for field "profile_models.model_inference.model_config_parameters.parameters" should be None  
        *  
        * Value for field "profile_models" must be a list, value is "{'model_inference': {'cpu_only': True, 'model_config_parameters': {'dynamic_batching': {'max_queue_delay_microseconds': [10, 100, 500, 1000, 10000, 50000, 100000]}, 'instance_group': [{'kind': 'KIND_CPU', 'count': [1, 2, 3, 4]}], 'parameters': [{'key': 'intra_op_thread_count', 'value': {'string_value': [1, 2, 3]}}]}}}". 
        * The value for field "profile_models" should not be a dictionary, current value is "{'model_inference': {'cpu_only': True, 'model_config_parameters': {'dynamic_batching': {'max_queue_delay_microseconds': [10, 100, 500, 1000, 10000, 50000, 100000]}, 'instance_group': [{'kind': 'KIND_CPU', 'count': [1, 2, 3, 4]}], 'parameters': [{'key': 'intra_op_thread_count', 'value': {'string_value': [1, 2, 3]}}]}}}". 

```
It is not clear in the [documentation](https://github.com/triton-inference-server/model_analyzer/blob/main/docs/config.md#model-config-parameters) whether it is possible to set the `intra_op_thread_count` parameter for testing.

Thank you in advance!

**Comment by tgerdesnv** [comment]
Hi @dmastapkovich,
Yes, it is possible to sweep over intra_op_thread_count.  You can sweep over any values supported by the triton config file.

Change this:
```
      parameters:
        - key: "intra_op_thread_count"
          value: 
            string_value: [1, 2, 3]
```

To this:
```
      parameters:
        intra_op_thread_count:
          string_value: ["1","2","3"]
```
