### ISSUE TITLE
how to use model_analyzer to profile BLS model？

### ISSUE THREAD

**Issue by DequanZhu** [triton-inference-server/model_analyzer#682]
I have a BLS model, the model exec infer request for another two ensemble model, here is my profile config file:
```
model_repository: /workspace/model_repository
run_config_search_mode: quick
run_config_search_max_instance_count: 12
run_config_search_max_concurrency: 32
run_config_search_min_model_batch_size: 1
run_config_search_max_model_batch_size: 32
profile_models:
  bls-test-model:             
    perf_analyzer_flags:
      input-data: /tmp/test-input-data.json     
bls_composing_models: ensemble-model-1,ensemble-model-2
```
But I got the error message `Model Analyzer does not support ensembles as a composing model type: ensemble-model-1`. According to the error message, it seems like model_analyzer don't support profile bls model which exec infer request for ensemble model, is it right?
