### ISSUE TITLE
How to assign different parameters in concurrent-multi-model-search for each model ?

### ISSUE THREAD

**Issue by monsterlyg** [triton-inference-server/model_analyzer#701]
I hope to profile several models concurrently using "quick" search mode. But each model has different max-batch-size. Based on the information learned from the "config_search.md" file,  model-config-paramters and parameters can only be used in "brute" search mode. 
And those configuration items like: 
run_config_search_max_instance_count: 3
run_config_search_min_model_batch_size: 16
run_config_search_min_concurrency: 8
run_config_search_max_concurrency: 256 
they will act on each model. In other words, I can not assign different max-batch-size for different model. 
Is my understanding wrong ? How can I assign different parameters in concurrent-multi-model-search for each model ?

**Comment by monsterlyg** [comment]
Model-analyzer did not search enough configs,  and no gpu metric
```
WARNING: Requested top 3 configs, but found only 1. Showing all available configs for this model.
...
[Model Analyzer] WARNING: No GPU metric corresponding to tag 'gpu_used_memory' found in the model's measurement. Possibly comparing measurements across devices.
```

here is my profile config, is there any problem with the config.yaml ? 
```
model_repository: "/ssd2/files/tritonSkillBall/models"
output_model_repository_path: "/ssd2/model-analyzer/profile_out/out_skillball"
checkpoint_directory: "/ssd2/model-analyzer/profile_out/checkpoint"
triton_output_path: "/ssd2/model-analyzer/triton_log/1.log"
export_path: "/ssd2/model-analyzer/profile_out/"
override_output_model_repository: true

run_config_search_disable: false
triton_launch_mode: 'local'
run_config_search_mode: 'quick'
run_config_profile_models_concurrently_enable: true

run_config_search_max_instance_count: 3
#run_config_search_max_model_batch_size: 4
run_config_search_min_concurrency: 1
run_config_search_max_concurrency: 16
num_configs_per_model: 3

client_protocol: "http"
triton_http_endpoint: 'localhost:4000'
triton_grpc_endpoint: 'localhost:4003'
triton_metrics_url: 'localhost:4002/metrics'

profile_models:
  - model_A
  - model_B
  - model_C

constraints:
  gpu_used_memory:
    max: 4096

perf_analyzer_flags:
  percentile: 95
```
