### ISSUE TITLE
model analyzer hangs for ensemble model with input type size as string 

### ISSUE THREAD

**Issue by anshudaur** [triton-inference-server/model_analyzer#764]
Hi, 

I am trying out to run the analyzer on ensemble model and the analyzer gets stuck : 
i was able to run the ensemble examples in the repo and on my own non-ensemble onnx model.

Ensemble models consists of a torchscript model with preprocessing and post processing steps . 

 the input expected by ensemble model is image bytes array as string .. could that be an issue ?
the minimal config is : 

```
platform: "ensemble"
max_batch_size: 0
input [
  {
    name: "image_bytes"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
] 
```

the commands used and the outputs as as follows :

1. I used the latest version as 23.09 py3 sdk image wasn't available, so i used 23.07 : 
```
docker pull nvcr.io/nvidia/tritonserver:23.07-py3-sdk
```

Run the following cmd  to run the profile on my model : 
/opt/triton-model-analyzer# model-analyzer profile \
>     --model-repository models \
>     --profile-models ensemble_v1 \
>     --triton-launch-mode=local --triton-docker-shm-size=4G \
>     --output-model-repository-path output/ensemble_v1 \
>     --export-path profile_results_ensemble --override-output-model-repository 

```

[Model Analyzer] Initializing GPUDevice handles
[Model Analyzer] Using GPU 0 Tesla V100-SXM2-32GB with UUID GPU-23272f1f-73da-6094-2380-d0c807233613
[Model Analyzer] WARNING: Overriding the output model repo path "output/ensemble_v1"
[Model Analyzer] Starting a local Triton Server
[Model Analyzer] No checkpoint file found, starting a fresh run.
[Model Analyzer] Profiling server only metrics...
[Model Analyzer] 
[Model Analyzer] Starting quick mode search to find optimal configs
[Model Analyzer] 
[Model Analyzer] Creating model config: preprocess_v1_config_default
[Model Analyzer] 
[Model Analyzer] Creating model config: detection_model_v1_config_default
[Model Analyzer] 
[Model Analyzer] Creating model config: postprocess_v1_config_default
[Model Analyzer] 
[Model Analyzer] Creating ensemble model config: ensemble_v1_config_default
```

After this it doesn't output anything , even after few hours.

So then i tried to directly run it on the detection model by providing an input using the following config : 

```
model_repository: 'models'

profile_models: 
- detection_model_v1

override_output_model_repository: true

triton_launch_mode: 'local'
client_protocol: 'http'
triton_http_endpoint: 'localhost:8000'

concurrency:
    start: 1
    stop: 1
    step: 1

batch_sizes:
    start: 1
    stop: 1
    step: 1

perf_analyzer_flags:
    percentile: 95
    shape: 'images__0:3,896,896'
```

But then it runs into Pytorch execute failure, as i guess the input was in the wrong format.
 Thread [0] had error: PyTorch execute failure: The following operation failed in the TorchScript interpreter.

Do you have suggestions on how i can fix it ? 
or how i can pass images as input to ensemble or the pytorch models ?

Thank you
Anshu
