### ISSUE TITLE
triton_server_flags does not allow to add keys: response-cache-byte-size or cache-config

### ISSUE THREAD

**Issue by suppagoddo** [triton-inference-server/model_analyzer#827]
I am running `model_analyzer` with triton in `local` launch mode. When try to set the `local` cache on triton using `cache-config` or `response-cache-byte-size` during the launch mode, `model_analyzer` fails with an error:

Error when using `cache-config`
`[Model Analyzer] Model Analyzer encountered an error: Failed to set the value for field "triton_server_flags". Error: Key "cache-config" should not be specified in field "triton_server_flags".`

Error when using `response-cache-byte-size`
`[Model Analyzer] Model Analyzer encountered an error: Failed to set the value for field "triton_server_flags". Error: Key "response-cache-byte-size" should not be specified in field "triton_server_flags".`

**Command to run model_analyzer:**
`model-analyzer -v profile -f config.yaml --triton-launch-mode=local --triton-http-endpoint=localhost:8001 --triton-grpc-endpoint=localhost:7989 --triton-metrics-url=http://localhost:7990/metrics --triton-output-path=/opt/logs/triton_inference_server_backend_model_analyzer.log --output-model-repository-path=/workspace/output --export-path profile_results --gpus=all`

**Config.yaml:**
```
model_repository: /opt/data/triton-current

run_config_search_disable: True

concurrency: [1]
batch_sizes: [1]

profile_models:
  causal_lm:
    model_config_parameters:
      instance_group:
        - kind: KIND_CPU
          count: [1]
      dynamic_batching:
        max_queue_delay_microseconds: [100]
      response_cache:
        enable: true
      optimization:
        graph:
          level: 1

triton_server_environment:
  response_cache_byte_size: 20485760
  response-cache-byte-size: 20485760
  cache-config: local,size=20485760
  cache_config: local,size=20485760

triton_server_flags:
  cache-config: local,size=20485760

perf_analyzer_flags:
  input-data: data.json
  shape:
    - input_ids:14
    - request_output_len:1
```

Triton Version: `22.12`
model_analyzer is: `nvidia/tritonserver:22.12-py3-sdk`
 
 I also tried using these two keys `response_cache_byte_size` and `cache_config` but the result is the same failure.
