### ISSUE TITLE
Ensemble Model search error when specify perf_analyzer_flags.input-data

### ISSUE THREAD

**Issue by harrymore** [triton-inference-server/model_analyzer#857]
I want to search for the best parameter for the Ensemble Model, the input of this Ensemble Model is a flattened 1D image data, so I need to specify the input-data，but when I code：
```
model-analyzer profile -f model_analyzer_config.yaml 
```
an error occurred:

> Model Analyzer] Initializing GPUDevice handles
[Model Analyzer] Using GPU 0 NVIDIA GeForce RTX 3060 Ti with UUID GPU-3b49d536-e111-0986-5544-226434230444
[Model Analyzer] WARNING: Overriding the output model repo path "/my-path-to-project/output_model_repository/test"
[Model Analyzer] Starting a Triton Server using docker
[Model Analyzer] No checkpoint file found, starting a fresh run.
[Model Analyzer] Profiling server only metrics...
[Model Analyzer] 
[Model Analyzer] Starting quick mode search to find optimal configs
[Model Analyzer] 
[Model Analyzer] Creating model config: disease_preprocess_config_default
[Model Analyzer] 
[Model Analyzer] Creating model config: disease_trt_config_default
[Model Analyzer] 
[Model Analyzer] Creating model config: disease_postprocess_config_default
[Model Analyzer] 
[Model Analyzer] Creating ensemble model config: disease_ensemble_config_default
[Model Analyzer] Profiling disease_ensemble_config_default: client batch size=1, concurrency=1
[Model Analyzer] Saved checkpoint to my-path-to-project/checkpoints/0.ckpt
Traceback (most recent call last):
  File "/usr/local/bin/model-analyzer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/entrypoint.py", line 278, in main
    analyzer.profile(
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/analyzer.py", line 124, in profile
    self._profile_models()
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/analyzer.py", line 248, in _profile_models
    self._model_manager.run_models(models=[model])
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/model_manager.py", line 142, in run_models
    measurement = self._metrics_manager.execute_run_config(run_config)
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/record/metrics_manager.py", line 230, in execute_run_config
    measurement = self.profile_models(run_config)
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/record/metrics_manager.py", line 296, in profile_models
    perf_config.extract_model_specific_parameters()
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/perf_analyzer/perf_config.py", line 298, in extract_model_specific_parameters
    "text-input-length": utils.extract_text_input_length_from_input_data(
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/config/generate/generator_utils.py", line 143, in extract_text_input_length_from_input_data
    _, _, text_input_length = input_data.split("-")
ValueError: not enough values to unpack (expected 3, got 2)

*shape of input:*
input [
  {
    name: "input_image"
    data_type: TYPE_UINT8
    dims: [ -1 ]
  }
]

*my search config:*
```yaml
model_repository: /my-path-to-project/model_repository
profile_models:
  - disease_ensemble
cpu_only_composing_models: disease_preprocess,disease_postprocess
perf_analyzer_flags:
  input-data: /my-path-to-project/test_imgs/data.json
triton_launch_mode: docker
triton_docker_shm_size: 1G
output_model_repository_path: /my-path-to-project/output_model_repository/test
override_output_model_repository: true
export_path: /my-path-to-project/profile_results
triton_docker_image: 192.168.1.200:8858/snapshots/gice-triton:v0.0.9
```
*docker image version:*
nvcr.io/nvidia/tritonserver:23.12-py3-sdk

*data.json*(some data is ignored):
```json
{"data": [{"input_image": {"content": [255, 216, 255,...,40, 3, 255, 217], "shape": [25127]}}]}
```
