### ISSUE TITLE
How to analyze large models like llama 3 70B that requires model parallelism?

### ISSUE THREAD

**Issue by ccchow** [triton-inference-server/model_analyzer#907]
The model engine is built from llama 3 70b with tensor parallelism tp=2 and pp=2 and deployed by below triton launch script:
python3 scripts/launch_triton_server.py --world_size 4 --model_repo=llama_ifb

In this case, how to leverage model-analyzer to analyze this parallelized model/deployment?

**Comment by nv-braf** [comment]
Are you able to run this model on PA or GenAI-Perf?

**Comment by ccchow** [comment]
I was able to use perf_analyzer to instrument llama 3 70b on 4*A100 (trtllm backend) via a launched triton server as below
```shell
python3 scripts/launch_triton_server.py --world_size 4 --model_repo=llama_ifb/
perf_analyzer -m ensemble --measurement-interval 10000 --concurrency-range <start:end:step> --input-data input.json
``` 

I'm wondering how can I tune triton model config using model analyzer in this case.

Thanks.

**Comment by LanceB57** [comment]
I'm in a very similar predicament, but with 8*H100. I'm getting pretty underwhelming results and would also like to know how to utilize model-analyzer, as I'm fairly new to Triton.

**Comment by the-david-oy** [comment]
Model Analyzer can profile your TP/PP deployment, but it can’t change the tensor/pipeline parallelism itself (those come from the TRT-LLM engine + launch_triton_server.py args). From MA’s point of view, your ensemble (or LLM) model is just a single Triton model that happens to span 4 GPUs.

You basically have two options:

**Treat Triton as a remote, fixed deployment.**

Since you’re already launching Triton with:
```
python3 scripts/launch_triton_server.py --world_size 4 --model_repo=llama_ifb/
```

you can let Model Analyzer only drive load + collect metrics, without trying to edit configs:

```
# config.yaml
triton_launch_mode: remote
triton_grpc_endpoint: localhost:8001
triton_http_endpoint: localhost:8000
triton_metrics_url: http://localhost:8002/metrics

model_repository: llama_ifb          # for naming/reporting only
profile_models:
  - ensemble                         # or your actual model name

run_config_search_disable: true      # remote mode can’t sweep configs

perf_analyzer_flags:
  measurement-interval: 10000
  concurrency-range: 1:64:4          # example
  input-data: input.json
```

Then run:

```bash
model-analyzer profile -f config.yaml
```

This gives you throughput/latency vs concurrency on your existing 4-GPU TP=2, PP=2 deployment, similar to how you’re using perf_analyzer today, but with MA’s reporting/checkpointing.

Note: in remote mode MA does not modify config.pbtxt or change TP/PP, by design.

**Sweep Triton config knobs.**

If you want MA to explore things like max_batch_size, dynamic batching, or instance_group (number of replicas), you’d need to:
- Put Triton + TRT-LLM + your engines + Model Analyzer in the same image.
- Run with triton_launch_mode: local (or docker) and a model_repository MA can write to.
- Keep TP/PP/world_size fixed in the TRT-LLM config, and only let MA adjust “normal” Triton settings.
